### ISSUE TITLE
error

### ISSUE THREAD

**Issue by astandarduser** [kiks7/frida-non-root#1]
I get error, not sure what I am doing wrong

C:\Python27\frida-non-root-master>py -2.7 main.py -i apk.apk -o apk2.apk
←[36m[*] Cleaning stuff if they already exists←[0m
←[36m[*] Decoding APK←[0m
Traceback (most recent call last):
  File "main.py", line 180, in <module>
    inject_smali(target)
  File "main.py", line 73, in inject_smali
    subprocess.call(['apktool', '-r', 'd', '-o', 'unpacked', target])
  File "C:\Python27\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by visualsayed** [comment]
It seems that it can't find apktool

**Comment by kiks7** [comment]
Sorry I was not supporting the project anymore. By the way, sorry but Windows is not supported (bash commands are used)
